<div class="rounded-box bg-base-200 my-5 p-5 md:p-8 lg:p-10 max-w-none prose prose-sm">
    <h1>Enhancements - HTML & CSS</h1>
    <h2>TailwindCSS</h2>
    <p>Implement <a href="https://tailwindcss.com">TailwindCSS</a> to design components used throughout the webpage.</p>
    <h2>Shopping cart - drawer</h2>
    <p>Shopping cart side drawer, which shows current items in cart. Will be implement to display cart data in Assignment 2</p>
</div>