<?php
$name = "Alister Klarica";
$title = "Data Scientist";
$student_id = "104004035";
$course = "Computer Science";
$image_url = "/images/members/alister.jpg";
$phone = "+61423514051";
$description = "<p>I'm Alister Klarica, I grew up in Australia, in an area with lots of trees and an unused train track.</p>
<p> I spend most of my free time playing League Of Legends, and my favourite movie is Scream.</p>";
$timetable = array (
    0 => 
    array (
      'day' => 'Monday',
      'sessions' => 
      array (
        0 => 
        array (
          'course' => 'COS10026',
          'type' => 'Online',
          'span' => 60,
        ),
        1 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        2 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        3 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        4 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        5 => 
        array (
          'course' => 'COS10026',
          'type' => 'Seminar',
          'span' => 60,
        ),
      ),
    ),
    1 => 
    array (
      'day' => 'Tuesday',
      'sessions' => 
      array (
        0 => 
        array (
          'course' => 'COS10009',
          'type' => 'Online',
          'span' => 120,
        ),
        1 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        2 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        3 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        4 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        5 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        6 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        7 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        8 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        9 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        10 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        11 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        12 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        13 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        14 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        15 => 
        array (
          'course' => 'COS10025',
          'type' => 'Seminar',
          'span' => 60,
        ),
        16 => 
        array (
          'course' => 'COS10009',
          'type' => 'Lab',
          'span' => 120,
        ),
      ),
    ),
    2 => 
    array (
      'day' => 'Wednesday',
      'sessions' => 
      array (
      ),
    ),
    3 => 
    array (
      'day' => 'Thursday',
      'sessions' => 
      array (
        0 => 
        array (
          'course' => 'COS10009',
          'type' => 'Workshop',
          'span' => 120,
        ),
        1 => 
        array (
          'course' => 'COS10026',
          'type' => 'Workshop',
          'span' => 120,
        ),
        2 => 
        array (
          'course' => 'COS10025',
          'type' => 'Workshop',
          'span' => 120,
        ),
      ),
    ),
    4 => 
    array (
      'day' => 'Friday',
      'sessions' => 
      array (
      ),
    ),
  )
?>