<?php
$name = "Huu Ti Dang";
$title = "Software Developer";
$student_id = "10410363";
$course = "Computer Science";
$phone = "+61424297762";
$image_url = "/images/members/huuti.jpg";
$description = '<p>Currently studying Software Development at Swinburne University of Technology.</p>
<p>From Da Nang, Vietnam</p>
<p>Love playing team-orientated and fast pace games</p>
';
$timetable = array (
    0 => 
    array (
      'day' => 'Monday',
      'sessions' => 
      array (
        0 => 
        array (
          'course' => 'COS10026',
          'type' => 'Online',
          'span' => 60,
        ),
        1 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        2 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        3 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        4 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        5 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        6 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        7 => 
        array (
          'course' => 'TNE10006',
          'type' => 'Lecture',
          'span' => 120,
        ),
        8 => 
        array (
          'course' => 'COS10004',
          'type' => 'Online',
          'span' => 60,
        ),
        9 => 
        array (
          'course' => 'COS10026',
          'type' => 'Seminar',
          'span' => 60,
        ),
      ),
    ),
    1 => 
    array (
      'day' => 'Tuesday',
      'sessions' => 
      array (
        0 => 
        array (
          'course' => 'COS10009',
          'type' => 'Online',
          'span' => 120,
        ),
      ),
    ),
    2 => 
    array (
      'day' => 'Wednesday',
      'sessions' => 
      array (
        0 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        1 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        2 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        3 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        4 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        5 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        6 => 
        array (
          'course' => 'TNE10006',
          'type' => 'Lab',
          'span' => 180,
        ),
      ),
    ),
    3 => 
    array (
      'day' => 'Thursday',
      'sessions' => 
      array (
        0 => 
        array (
          'course' => 'COS10009',
          'type' => 'Lab',
          'span' => 120,
        ),
        1 => 
        array (
          'course' => 'COS10026',
          'type' => 'Workshop',
          'span' => 120,
        ),
        2 => 
        array (
          'course' => 'COS10009',
          'type' => 'Workshop',
          'span' => 120,
        ),
      ),
    ),
    4 => 
    array (
      'day' => 'Friday',
      'sessions' => 
      array (
        0 => 
        array (
          'course' => 'COS10004',
          'type' => 'Lab',
          'span' => 120,
        ),
      ),
    ),
  )
?>