<?php
$name = "Nguyen Quang Huy Pham";
$title = "Cybersecurity";
$student_id = "103826322";
$course = "Computer Science";
$image_url = "images/members/huy.jpg";
$phone = "+61434177988";
$description = '<p>Hey, I’m Huy but people here call me Bill. I grew up in Vietnam, and lived there before I study aboard in Australia.</p>
<p>I speak Vietnamese and English. I love gaming, and I play Fifa 19 almost every day with my friends.</p>
<p>My favorite book is “Diary of the wimpy kid”, this book is very engaging.</p>
';
$timetable = array (
    0 => 
    array (
      'day' => 'Monday',
      'sessions' => 
      array (
        0 => 
        array (
          'course' => 'COS10026',
          'type' => 'Online',
          'span' => 60,
        ),
        1 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        2 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        3 => 
        array (
          'course' => 'COS10026',
          'type' => 'Seminar',
          'span' => 60,
        ),
        4 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        5 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        6 => 
        array (
          'course' => 'TNE10006',
          'type' => 'Lecture',
          'span' => 120,
        ),
        7 => 
        array (
          'course' => 'COS10004',
          'type' => 'Online',
          'span' => 60,
        ),
        8 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        9 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        10 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        11 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        12 => 
        array (
          'course' => 'TNE10006',
          'type' => 'Lab',
          'span' => 180,
        ),
      ),
    ),
    1 => 
    array (
      'day' => 'Tuesday',
      'sessions' => 
      array (
        0 => 
        array (
          'course' => 'COS10009',
          'type' => 'Online',
          'span' => 120,
        ),
        1 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        2 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        3 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        4 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        5 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        6 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        7 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        8 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        9 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        10 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        11 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        12 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        13 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        14 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        15 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        16 => 
        array (
          'course' => 'COS10009',
          'type' => 'Lab',
          'span' => 120,
        ),
      ),
    ),
    2 => 
    array (
      'day' => 'Wednesday',
      'sessions' => 
      array (
      ),
    ),
    3 => 
    array (
      'day' => 'Thursday',
      'sessions' => 
      array (
        0 => 
        array (
          'course' => 'COS10004',
          'type' => 'Lab',
          'span' => 120,
        ),
        1 => 
        array (
          'course' => 'COS10026',
          'type' => 'Workshop',
          'span' => 120,
        ),
        2 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        3 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        4 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        5 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        6 => 
        array (
          'course' => 'COS10009',
          'type' => 'Workshop',
          'span' => 120,
        ),
      ),
    ),
    4 => 
    array (
      'day' => 'Friday',
      'sessions' => 
      array (
      ),
    ),
  )
?>