<?php
$name = "Nguyen Linh Bao Nguyen";
$title = "Software Developer";
$student_id = "103842645";
$course = "Computer Science";
$image_url = "images/members/bao.jpg";
$phone = "+61424395642";
$description = '
<p>Honour awards: <i>rank 9th in competitive programming contest</i></p>

<dl>
    <dt class="font-bold">Skills:</dt>
        <dd class="ml-2">Critical thinking</dd>
        <dd class="ml-2">Logical thinking</dd>
        <dd class="ml-2">Complex problem-solving</dd>
        <dd class="ml-2">Time management</dd>
    <dt class="font-bold">Programming languages that I know:</dt>
        <dd class="ml-2">Ruby</dd>
        <dd class="ml-2">Python</dd>
        <dd class="ml-2">HTML</dd>
        <dd class="ml-2">CSS</dd>
    <dt class="font-bold">Interests:</dt>
        <dd class="ml-2">Reading</dd>
        <dd class="ml-2">Politics</dd>
        <dd class="ml-2">Gym</dd>
        <dd class="ml-2">Coding</dd>
        <dd class="ml-2">Listening to music</dd>
</dl>
';
$timetable = array (
    0 => 
    array (
      'day' => 'Monday',
      'sessions' => 
      array (
        0 => 
        array (
          'course' => 'COS10026',
          'type' => 'Online',
          'span' => 60,
        ),
        1 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        2 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        3 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        4 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        5 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        6 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        7 => 
        array (
          'course' => 'TNE10006',
          'type' => 'Lecture',
          'span' => 120,
        ),
        8 => 
        array (
          'course' => 'COS10004',
          'type' => 'Online',
          'span' => 60,
        ),
        9 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        10 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        11 => 
        array (
          'course' => 'COS10026',
          'type' => 'Seminar',
          'span' => 60,
        ),
      ),
    ),
    1 => 
    array (
      'day' => 'Tuesday',
      'sessions' => 
      array (
        0 => 
        array (
          'course' => 'COS10009',
          'type' => 'Online',
          'span' => 120,
        ),
        1 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        2 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        3 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        4 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        5 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        6 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        7 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        8 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        9 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        10 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        11 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        12 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        13 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        14 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        15 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        16 => 
        array (
          'course' => 'COS10009',
          'type' => 'Lab',
          'span' => 120,
        ),
      ),
    ),
    2 => 
    array (
      'day' => 'Wednesday',
      'sessions' => 
      array (
        0 => 
        array (
          'course' => 'TNE10006',
          'type' => 'Lab',
          'span' => 180,
        ),
        1 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        2 => 
        array (
          'course' => NULL,
          'type' => NULL,
          'span' => 30,
        ),
        3 => 
        array (
          'course' => 'COS10009',
          'type' => 'Workshop',
          'span' => 120,
        ),
      ),
    ),
    3 => 
    array (
      'day' => 'Thursday',
      'sessions' => 
      array (
        0 => 
        array (
          'course' => 'COS10004',
          'type' => 'Lab',
          'span' => 120,
        ),
        1 => 
        array (
          'course' => 'COS10026',
          'type' => 'Workshop',
          'span' => 120,
        ),
      ),
    ),
    4 => 
    array (
      'day' => 'Friday',
      'sessions' => 
      array (
      ),
    ),
);
?>