<!-- START CATEGORIES -->
<div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 mx-2 md:mx-0">
  <div class="hero h-72 rounded-xl" id="category-pizza">
    <a href="product.php" class="hero-overlay bg-opacity-60 hover:bg-opacity-90 transition ease-in duration-500 rounded-xl"></a>
    <div class="hero-content text-center text-primary-content">
      <div class="max-w-md">
        <h1 class="mb-5 text-5xl font-bold">Pizza</h1>
      </div>
    </div>
  </div>
  <div class="hero h-72 rounded-xl" id="category-pasta">
    <a href="product.php" class="hero-overlay bg-opacity-60 hover:bg-opacity-90 transition ease-in duration-500 rounded-xl"></a>
    <div class="hero-content text-center text-primary-content">
      <div class="max-w-md">
        <h1 class="mb-5 text-5xl font-bold">Pasta</h1>
      </div>
    </div>
  </div>
  <div class="hero h-72 rounded-xl" id="category-wings">
    <a href="product.php" class="hero-overlay bg-opacity-60 hover:bg-opacity-90 transition ease-in duration-500 rounded-xl"></a>
    <div class="hero-content text-center text-primary-content">
      <div class="max-w-md">
        <h1 class="mb-5 text-5xl font-bold">Wings</h1>
      </div>
    </div>
  </div>
  <div class="hero h-72 rounded-xl" id="category-sides">
    <a href="product.php" class="hero-overlay bg-opacity-60 hover:bg-opacity-90 transition ease-in duration-500 rounded-xl"></a>
    <div class="hero-content text-center text-primary-content">
      <div class="max-w-md">
        <h1 class="mb-5 text-5xl font-bold">Sides</h1>
      </div>
    </div>
  </div>
  <div class="hero h-72 rounded-xl" id="category-desserts">
    <a href="product.php" class="hero-overlay bg-opacity-60 hover:bg-opacity-90 transition ease-in duration-500 rounded-xl"></a>
    <div class="hero-content text-center text-primary-content">
      <div class="max-w-md">
        <h1 class="mb-5 text-5xl font-bold">Desserts</h1>
      </div>
    </div>
  </div>
  <div class="hero h-72 rounded-xl" id="category-drinks">
    <a href="product.php" class="hero-overlay bg-opacity-60 hover:bg-opacity-90 transition ease-in duration-500 rounded-xl"></a>
    <div class="hero-content text-center text-primary-content">
      <div class="max-w-md">
        <h1 class="mb-5 text-5xl font-bold">Drinks</h1>
      </div>
    </div>
  </div>
  <div class="hero h-72 rounded-xl" id="category-meals">
    <a href="product.php" class="hero-overlay bg-opacity-60 hover:bg-opacity-90 transition ease-in duration-500 rounded-xl"></a>
    <div class="hero-content text-center text-primary-content">
      <div class="max-w-md">
        <h1 class="mb-5 text-5xl font-bold">Meals</h1>
      </div>
    </div>
  </div>
</div>
<!-- END CATEGORIES -->
