<div class="my-5 grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
    <a class="card bg-base-100 shadow hover:shadow-xl transition ease-in-out delay-500" href="member.php?member=minhpg">
        <figure class="h-1/2">
            <img src="images/members/minhpg.jpg" alt="member-image" class="h-full" />
        </figure>
        <div class="card-body p-4 mt-3 flex flex-col justify-between">
            <div class="w-full">
                <h2 class="card-title text-2xl">
                    Gia Minh Pham
                </h2>
                <h3 class="card-subtitle">Data Scientist</h3>
            </div>
            <div class="mt-5">
                <p class="font-light">Currently studying Major of Data Science at Swinburne</p>
            </div>
        </div>
    </a>
    <a class="card bg-base-100 shadow hover:shadow-xl transition ease-in-out delay-500" href="member.php?member=huy">
        <figure class="h-1/2">
            <img src="images/members/huy.jpg" alt="member-image" class="h-full" />
        </figure>
        <div class="card-body p-4 mt-3 flex flex-col justify-between">
            <div class="w-full">
                <h2 class="card-title text-2xl">
                    Nguyen Quang Huy Pham
                </h2>
                <h3 class="card-subtitle">Cybersecurity</h3>
            </div>
            <div class="mt-5">
                <p class="font-light">Currently studying Major of Cybersecurity at Swinburne</p>
            </div>
        </div>
    </a>
    <a class="card bg-base-100 shadow hover:shadow-xl transition ease-in-out delay-500" href="member.php?member=linhbao">
        <figure class="h-1/2">
            <img src="images/members/bao.jpg" alt="member-image" class="h-full" />
        </figure>
        <div class="card-body p-4 mt-3 flex flex-col justify-between">
            <div class="w-full">
                <h2 class="card-title text-2xl">
                Nguyen Linh Bao Nguyen
                </h2>
                <h3 class="card-subtitle">Software Developer</h3>
            </div>
            <div class="mt-5">
                <p class="font-light">Currently studying Software Development at Swinburne</p>
            </div>
        </div>
    </a>
    <a class="card bg-base-100 shadow hover:shadow-xl transition ease-in-out delay-500" href="member.php?member=huuti">
        <figure class="h-1/2">
            <img src="images/members/huuti.jpg" alt="member-image" class="h-full" />
        </figure>
        <div class="card-body p-4 mt-3 flex flex-col justify-between">
            <div class="w-full">
                <h2 class="card-title text-2xl">
                Huu Ti Dang
                </h2>
                <h3 class="card-subtitle">Software Developer</h3>
            </div>
            <div class="mt-5">
                <p class="font-light">Currently studying Software Development at Swinburne</p>
            </div>
        </div>
    </a>
    <a class="card bg-base-100 shadow hover:shadow-xl transition ease-in-out delay-500" href="member.php?member=alister">
        <figure class="h-1/2">
            <img src="images/members/alister.jpg" alt="member-image" class="h-full" />
        </figure>
        <div class="card-body p-4 mt-3 flex flex-col justify-between">
            <div class="w-full">
                <h2 class="card-title text-2xl">
                    Alister Klarica
                </h2>
                <h3 class="card-subtitle">Data Scientist</h3>
            </div>
            <div class="mt-5">
                <p class="font-light">Currently studying Major of Data Science at Swinburne</p>
            </div>
        </div>
    </a>
</div>